version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PIP_REGISTRY=https://pypi.tuna.tsinghua.edu.cn/simple
        - APK_REGISTRY=dl-cdn.alpinelinux.org/mirrors.tuna.tsinghua.edu.cn

    ports:
      - ${DeployPort}:8000
    environment:
      - TERM_START_DATE=${TERM_START_DATE}
      - COURSE_TTF=${COURSE_TTF}